# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.9'

services:
  tests:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/code
    command: bash -c "cd /code && dotnet test"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  testweb:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ConnectionStrings__LitExplore: null
      ASPNETCORE_URLS: https://+;http://+ # taken from ondfisk repo maybe for usage later
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: skrrrt
    ports:
      - 5141:5141
      - 7252:7252
      - 80:80
      - 443:443
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__LitExplore
    volumes: #C:\Users\Thomas\Desktop\school\sem3\bdsa\BDSAExamProject
      - ./secrets/:/https/

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt
